name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build-website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        working-directory: website
        run: npm install
      - name: Build website
        working-directory: website
        run: npm run build
      - name: Upload website dist
        uses: actions/upload-artifact@v1
        with:
          name: website-dist
          path: website/build

  build-server:
    needs: build-website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download website dist
        uses: actions/download-artifact@v1
        with:
          name: website-dist
      - name: Copy website dist
        run: |
          mkdir server-local-cli/src/main/resources/website
          cp -a website-dist/** server-local-cli/src/main/resources/website
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build with Gradle
        run: |
          ./gradlew build
          VERSION=$(./gradlew properties -no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
      - name: Upload server-local-cli.jar
          uses: actions/upload-artifact@v1
          with:
            name: server-local-cli.jar
            path: server-local-cli/build/libs/server-local-cli-$VERSION.jar

  publish-snapshot:
    needs: build-server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download website dist
        uses: actions/download-artifact@v1
        with:
          name: website-dist
      - name: Copy website dist
        run: |
          mkdir server-local-cli/src/main/resources/website
          cp -a website-dist/** server-local-cli/src/main/resources/website
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}

  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish-release:
    needs: build-server
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download website dist
        uses: actions/download-artifact@v1
        with:
          name: website-dist
      - name: Copy website dist
        run: |
          mkdir server-local-cli/src/main/resources/website
          cp -a website-dist/** server-local-cli/src/main/resources/website
      - name: Publish with Gradle
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          ./gradlew -Pdstack_version=$VERSION clean publish -Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}