name: Build with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        working-directory: website
        run: npm install
      - name: Build website
        working-directory: website
        run: npm run build
      - name: Upload website dist
        uses: actions/upload-artifact@v1
        with:
          name: website-dist
          path: website/build

  build-server:

    needs: build-website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download website dist
        uses: actions/download-artifact@v1
        with:
          name: website-dist
      - name: Copy website dist
          run: cp -a website-dist/** server-base-local/src/main/resources/website
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  publish-snapshot:

    needs: build-server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download website dist
        uses: actions/download-artifact@v1
        with:
          name: website-dist
      - name: Copy website dist
          run: cp -a website-dist/** server-base-local/src/main/resources/website
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
